version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    # ports:
    #   - "0.0.0.0:3306:3306"
    environment:
      MYSQL_DATABASE: bh
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysqlData:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  app:
    image: baihu:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: bh
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
    ports:
      - "0.0.0.0:80:5600"
    volumes:
      - ./data:/bh/dist/data
